### PR TITLE
Added dockerfile

### PR DESCRIPTION
**Pull request by andrej-s**
Hello, thank you for this great project! I am using tempo inside a Docker container and thought you might be interested in adding this to your repo.

Anyways, thanks again, Agate.

### CODE REVIEW

**Review by agateblue — COMMENTED** [review]
Thank you for this! I have tested locally and it works great. I wanted to add a couple small changes before merging but unfortunately I don't have the permission to edit your branch.

Do you think you could add a `.dockerignore` file containing `node_modules/` and the following section at the end of the README.md?

### Deploying using Docker

If you want to deploy Tempo using Docker, you can use our Dockerfile:

```bash
docker build -t tempo .
docker run --rm -p 8097:80 tempo
```

The image includes an Nginx server and a compiled bundle of Tempo assets.

---

**Comment by andrej-s** [comment]
More than happy to do so, @agateblue - one question though: I am not sure adding node_modules to a dockerignore file, as there is no such folder on your repo, and when copying data to the final image, we only copy the build folder - the final image is as sleek as can be. Maybe I am misunderstanding. Just let me know if you'd like me to still add a dockerignore and I'll happily oblige.

**Comment by agateblue** [comment]
> More than happy to do so, @agateblue - one question though: I am not sure adding node_modules to a dockerignore file, as there is no such folder on your repo, and when copying data to the final image, we only copy the build folder - the final image is as sleek as can be. Maybe I am misunderstanding. Just let me know if you'd like me to still add a dockerignore and I'll happily oblige.

Sorry, I should have given more context: in a local/dev environment where you try or work on Tempo with and without docker, node_modules exists and building the image can take a while because this folder is passed into the docker build context ;)

**Comment by andrej-s** [comment]
Perfect, makes sense! I followed both your suggestions.

**Review by agateblue — APPROVED** [review]
Perfect, thanks again for your help on this :)

**Pull request merged**
